### ISSUE TITLE
Markup Not Working in Azure Pipelines

### ISSUE THREAD

**Issue by elzik** [spectreconsole/spectre.console#1666]
**Information**
 - OS: Linux Ubuntu 22.04.5 build agent
 - Version: Spectre.Console 0.49.1
 - Terminal: Azure pipeline output

**Describe the bug**
When a console app built using Spectre.Console is run from an Azure pipeline PowerShell task, the output does not honour the colours set.

**To Reproduce**
1. Create a simple .NET console application and reference Spectre.Console
2. Execute this single line in the console application:
```csharp
AnsiConsole.MarkupLine("[green]This should be green but isn't[/]");
```
3. Run the console application from a `PowerShell@2`:
```yaml
- task: PowerShell@2
  displayName: 'Test Script'
  inputs:
    targetType: 'inline'
    script: |
      Write-Host "`e[32mThis should be green and is`e[0m"
      test-console-application
```

**Expected behavior**
Both lines written to the console should be green. The first is using an ANSI escape code, and the second is using Spectre.Console. However, as seen in the screenshot, only the first line is green.

**Screenshots**
![image](https://github.com/user-attachments/assets/7af62a8b-ba7d-4ee7-ae27-6e8615cec775)

---
Please upvote :+1: this issue if you are interested in it.
