### ISSUE TITLE
Infer# scan reports null derefences, resource leaks and race conditions

### ISSUE THREAD

**Issue by veikkoeeva** [spectreconsole/spectre.console#664]
**Information**

 - OS: Linux
 - Version: 0.43.0

**Describe the bug**

The clearest listing of the problems is available at https://github.com/lumoin/Verifiable/pull/48/checks?check_run_id=4554484579. The built results are also downloadable at https://github.com/lumoin/Verifiable/actions/runs/1589304607.

**To Reproduce**

I added [Infer#](https://github.com/microsoft/infersharpaction) as a step, inspectable at https://github.com/lumoin/Verifiable/pull/48/files#diff-7829468e86c1cc5d5133195b5cb48e1ff6c75e3e9203777f6b2e379d9e4882b3R191. I do not know if there is an easy way to run this from a command line. It also appears if there were, the command line application would work only under Linux due to the library's dependency on a Facebook library that works only under Linux.

The commands are slightly modified from the [Infer#]() documentation, just full path information added. Added here in case the links become unavailable or if needed for later.

```
- name: Run Infer#
   if: ${{ matrix.os == 'ubuntu-latest' }}
   uses: microsoft/infersharpaction@v1.2.1
   with:
     binary-path: ./src/${{ env.VERIFIABLE }}/bin/${{ env.BUILD_CONFIGURATION }}

- name: Show Infer# analysis results
   id: runinfersharp
   if: ${{ matrix.os == 'ubuntu-latest' }}
   run: echo ${{ github.workspace }}/infer-out/report.txt

- name: Upload Infer# report
   if: ${{ matrix.os == 'ubuntu-latest' }}
   uses: actions/upload-artifact@v2
   with:
     name: Infer# report
     path: ${{ github.workspace }}/infer-out/report.txt

- name: Upload SARIF output to GitHub Security Center
   if: ${{ matrix.os == 'ubuntu-latest' }}
   uses: github/codeql-action/upload-sarif@v1
   with:
     sarif_file: ${{ github.workspace }}/infer-out/report.sarif
```

**Expected behavior**

[Infer#](https://github.com/microsoft/infersharpaction) does not report problems or that they are publicly known problems.

**Additional context**

An example image in case the link to problem reports become unavilable.
![kuva](https://user-images.githubusercontent.com/5158694/146448586-5b7491d9-fdaf-4cda-8d82-b3ddc97eabf3.png)
